-- USERS
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255),
    full_name VARCHAR(255),
    dob DATE,
    gender VARCHAR(50),
    phone VARCHAR(255),
    password VARCHAR(255),
    address VARCHAR(255),
    image_url VARCHAR(255),
    CONSTRAINT users_gender_check CHECK (gender IN ('MALE', 'FEMALE', 'OTHER'))
);

ALTER TABLE users ADD CONSTRAINT unique_username UNIQUE (username);
ALTER TABLE users ADD CONSTRAINT unique_email UNIQUE (email);

-- PROJECT
CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    created_at TIMESTAMP,
    created_by BIGINT
);

-- PROJECT MEMBER
CREATE TABLE project_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT,
    user_id BIGINT,
    role VARCHAR(50),
    joined_at TIMESTAMP,
    CONSTRAINT project_member_role_check CHECK (role IN ('LEADER', 'MEMBER'))
);

-- TASK
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    status VARCHAR(50),
    deadline TIMESTAMP,
    created_at TIMESTAMP,
    project_id BIGINT,
    assignee_id BIGINT,
    CONSTRAINT task_status_check CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE', 'PAUSED', 'CANCELLED'))
);

-- USER ROLES (ElementCollection)
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50),
    CONSTRAINT user_roles_role_check CHECK (role IN ('ADMIN', 'MANAGER', 'MEMBER')),
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role)
);

-- FOREIGN KEYS
ALTER TABLE project
    ADD CONSTRAINT fk_project_created_by
        FOREIGN KEY (created_by) REFERENCES users(id);

ALTER TABLE project_member
    ADD CONSTRAINT fk_pm_project
        FOREIGN KEY (project_id) REFERENCES project(id);

ALTER TABLE project_member
    ADD CONSTRAINT fk_pm_user
        FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE task
    ADD CONSTRAINT fk_task_project
        FOREIGN KEY (project_id) REFERENCES project(id);

ALTER TABLE task
    ADD CONSTRAINT fk_task_assignee
        FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(id);