
CREATE TABLE public.task_attachments (
    sad
    id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    type VARCHAR(50) NOT NULL,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT task_attachments_pkey PRIMARY KEY (id),

    CONSTRAINT fk_task_attachment_task
     FOREIGN KEY (task_id)
         REFERENCES public.task(id)
         ON DELETE CASCADE,

    CONSTRAINT fk_task_attachment_user
     FOREIGN KEY (user_id)
         REFERENCES public.users(id)
         ON DELETE CASCADE
);

ALTER TABLE public.task_attachments
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE public.task_comments (
    id BIGINT NOT NULL,
    content TEXT NOT NULL,
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT task_comments_pkey PRIMARY KEY (id),

    CONSTRAINT fk_task_comment_task
      FOREIGN KEY (task_id)
          REFERENCES public.task(id)
          ON DELETE CASCADE,

    CONSTRAINT fk_task_comment_user
      FOREIGN KEY (user_id)
          REFERENCES public.users(id)
          ON DELETE CASCADE,

    CONSTRAINT fk_task_comment_parent
      FOREIGN KEY (parent_comment_id)
          REFERENCES public.task_comments(id)
          ON DELETE CASCADE
);

ALTER TABLE public.task_comments
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX idx_task_attachments_task_id ON public.task_attachments(task_id);
CREATE INDEX idx_task_attachments_user_id ON public.task_attachments(user_id);

CREATE INDEX idx_task_comments_task_id ON public.task_comments(task_id);
CREATE INDEX idx_task_comments_user_id ON public.task_comments(user_id);
CREATE INDEX idx_task_comments_parent_id ON public.task_comments(parent_comment_id);