CREATE TABLE public.meetings (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    start_time timestamp(6) without time zone NOT NULL,
    end_time timestamp(6) without time zone NOT NULL,
    room_code character varying(50) NOT NULL,
    project_id bigint NOT NULL,
    organizer_id bigint NOT NULL
);

ALTER TABLE public.meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_room_code_key UNIQUE (room_code);

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fk_meetings_project FOREIGN KEY (project_id) REFERENCES public.project(id);

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fk_meetings_organizer FOREIGN KEY (organizer_id) REFERENCES public.users(id);

CREATE TABLE public.meeting_participants (
    meeting_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT meeting_participants_pkey PRIMARY KEY (meeting_id, user_id);

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT fk_meeting_participants_meeting FOREIGN KEY (meeting_id) REFERENCES public.meetings(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT fk_meeting_participants_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;