CREATE TABLE revinfo (
    id bigint NOT NULL,
    timestamp bigint NOT NULL,
    username character varying(255),
    ip_address character varying(100)
);

CREATE SEQUENCE IF NOT EXISTS revinfo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE revinfo
    ALTER COLUMN id SET DEFAULT nextval('revinfo_seq');

SELECT setval('revinfo_seq', COALESCE((SELECT MAX(id) FROM revinfo), 0) + 1, false);
ALTER SEQUENCE revinfo_seq OWNED BY revinfo.id;

ALTER TABLE ONLY revinfo
    ADD CONSTRAINT revinfo_pkey PRIMARY KEY (id);

CREATE TABLE activity_log (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    project_id bigint NOT NULL,
    action character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    entity_id bigint NOT NULL,
    description text,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE activity_log
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY activity_log
    ADD CONSTRAINT fk_activity_log_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY activity_log
    ADD CONSTRAINT fk_activity_log_project FOREIGN KEY (project_id) REFERENCES project(id);

CREATE INDEX idx_activity_entity
    ON activity_log(type, entity_id);

CREATE INDEX idx_activity_user
    ON activity_log(user_id);

CREATE INDEX idx_activity_project
    ON activity_log(project_id);

CREATE INDEX idx_activity_created
    ON activity_log(created_at);